### ISSUE TITLE
No default set for size of 'group' collection thread pool

### ISSUE THREAD

**Issue by franc0is** [stripe/gaps#12]
I've been seeing a fair bit of crashes due to mongo connection timeout.
```
[1] Finding all groups containing email (page: 0): uri="https://www.googleapis.com/admin/directory/v1/groups?domain=pulse-dev.net&userKey=firmware_analytics%40pulse-dev.net"
/gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/connection/pool.rb:261:in `block in checkout': could not obtain connection within 5.0 seconds. The max pool size is currently 1; consider increasing the pool size or timeout. (Mongo::ConnectionTimeoutError)
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/connection/pool.rb:259:in `loop'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/connection/pool.rb:259:in `checkout'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/mongo_client.rb:516:in `checkout_reader'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/cursor.rb:620:in `checkout_socket_from_connection'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/cursor.rb:547:in `block in send_initial_query'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/functional/logging.rb:55:in `block in instrument'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/functional/logging.rb:20:in `instrument'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/functional/logging.rb:54:in `instrument'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/cursor.rb:544:in `send_initial_query'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/cursor.rb:529:in `refresh'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/cursor.rb:136:in `next'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/collection.rb:329:in `find_one'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/plucky-0.6.6/lib/plucky/query.rb:85:in `find_one'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/mongo_mapper-0.13.1/lib/mongo_mapper/plugins/identity_map.rb:129:in `find_one'
	from /gaps/lib/gaps/db/user.rb:32:in `lister'
	from /gaps/lib/gaps/db/group.rb:155:in `memberships'
	from /gaps/lib/gaps/db/group.rb:286:in `block (2 levels) in warm_transitive_closure_cache'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/future.rb:27:in `block in initialize'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:56:in `execute'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:384:in `block (2 levels) in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `loop'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/thread-0.1.4/lib/thread/pool.rb:351:in `block in spawn_thread'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /gaps/vendor/bundle/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

Heeding the error message's recommendation to increase the size of the thread pool, I looked into where the defaults are set. Turns out, only the 'cache' collection has a default (set to 10), but not the 'group' collection.

I addressed this in my `site.yaml`, but it would perhaps make sense to set a better default in `config.yaml'

**Comment by gdb** [comment]
Hm, what setting did you set, exactly? The `pool_size` config setting (https://github.com/stripe/gaps/blob/master/config.yaml#L8) is used for both threadpools we allocate. I wouldn't expect that changing a setting in `config.yaml` would help, but maybe I'm missing something.

I believe that the error message refers to the Mongo driver's internal connection pool. Is that right? If so, it seems reasonable to me to boost that (but I don't think we have any code that does so yet).

**Comment by franc0is** [comment]
Ah, you're right. I should have read more carefully. The threadpool is used for both cache and group collections.
`@thread_pool ||= Thread::Pool.new(configatron.cache.pool_size)` in group.rb

I was just grepping around for a knob I could turn to increase the size of the thread pool that the mongo driver is complaining about and all I could find were the thread pools in cache.rb and group.rb.

**Comment by gdb** [comment]
Just bumped the Mongo pool size. Let me know if that seems to work for you.

**Comment by franc0is** [comment]
Deployed. I'll report whether or not it's still up in a couple of days.

**Comment by franc0is** [comment]
@gdb following up: bumping up the Mongo pool size seems to have resolved our stability issues. Our instance of gaps has been up since we deployed the change. Thanks again!

**Comment by gdb** [comment]
Awesome to hear!
