### ISSUE TITLE
Heroku Mongo Authentication

### ISSUE THREAD

**Issue by bbrock25** [stripe/gaps#21]
When using the Heroku and MongoLabs for running this application, we're getting failure when trying to authenticate the user.

```
2015-11-22T20:41:58.936994+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/connection/pool.rb:320:in `block in check_auths'
2015-11-22T20:41:58.936996+00:00 app[web.1]:    from /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/set.rb:263:in `each'
2015-11-22T20:41:58.936931+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/mongo-1.11.1/lib/mongo/functional/authentication.rb:205:in `issue_authentication': Failed to authenticate user
```

This doesn't reproduce locally, most likely due to differences in the mongo versions. I'm running mongo v3.0.6 locally. 

Has anyone else been experiencing this issue?

**Comment by mikenikles** [comment]
I just ran into the same issue. It looks like mongo-mapper hasn't been well maintained with the latest release in November 2014. The mongo dependency mongo-mapper uses (https://github.com/mongomapper/mongomapper/blob/master/gemfiles/Gemfile.common.rb#L10) is most likely not compatible with MongoLabs 3.x DBs
